FROM python:3.12-slim

WORKDIR /app

# Copy the project root files, including setup.py and common
COPY ../setup.py /app/
COPY ../common /app/common

# Copy application-specific files
COPY . /app/account-service

WORKDIR /app/account-service

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -e ..

ENV PYTHONPATH=/app

EXPOSE 8081

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8081", "--workers", "4"]
