apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: banking
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
