apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: fintechapp
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
    target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: fintechapp

configMapGenerator:
  - name: fintechapp-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug

images:
  - name: ghcr.io/sankarikals/fintechapp
    newTag: dev
