apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-green
  namespace: banking
  labels:
    app: auth-service
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      color: green
  template:
    metadata:
      labels:
        app: auth-service
        color: green
    spec:
      containers:
      - name: auth-service
        image: akhilmittal510/auth-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "account123"
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DB
          value: banking
        - name: PYTHONPATH
          value: "/app/auth-service"
        - name: OTEL_LOG_LEVEL
          value: DEBUG
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        - name: OTEL_SERVICE_NAME
          value: "auth-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
